name: Portfolio CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # 1. Checkout code
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  # 2. Lint & validate code
  lint_validate:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint HTML
        run: |
          npx htmlhint "**/*.html"

      - name: Lint CSS
        run: |
          npm init stylelint
          npx stylelint "**/*.css"

      - name: Lint JS
        run: |
          npm init @eslint/config@latest
          npx eslint "**/*.js" 

